AWSTemplateFormatVersion: 2010-09-09
Description: >-
  weather-forecast-app

Transform:
- AWS::Serverless-2016-10-31

Resources:
  mainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/main.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole